### ISSUE TITLE
Roguelike.Utils.contains

### ISSUE THREAD

**Issue by unstoppablecarl** [stefanweck/dungeongeneration#6]
https://github.com/stefanweck/dungeongeneration/blob/master/lib/core/utils.js#L68

`Array.prototype.indexOf(obj)` already does this is there a reason you recreated it in this function?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf

**Comment by stefanweck** [comment]
I'm changing it right away, seems like that function has been there since the beginning of this project. I'm already using indexOf throughout my other functions. Thanks for reporting, saves me a few lines of code :+1:
